name: build-push

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
    - "main"
  pull_request:
    branches:
    - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: yarn install
      - run: yarn test
      - uses: JS-DevTools/npm-publish@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public